// Builds public/js/cities.js from the GeoNames dumps in tools/data/ (see README). No dependencies.
// Run: node tools/build-cities.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const data = new URL('./data/', import.meta.url);
const out = new URL('../public/js/cities.js', import.meta.url);
const lines = file => readFileSync(new URL(file, data), 'utf8').split('\n').filter(Boolean).map(l => l.split('\t'));

// Keep the output one clean line per city, and keep U+2013/U+2014 out of public/.
const DASHES = new RegExp('[' + String.fromCharCode(0x2013, 0x2014) + ']', 'g');
const clean = s => (s || '').replace(/[|\s]+/g, ' ').replace(DASHES, '-').trim();
const admin1 = new Map(lines('admin1CodesASCII.txt').map(f => [f[0], clean(f[1])]));

const zoneOk = new Map();
function validZone(tz) {
  if (!zoneOk.has(tz)) {
    try { new Intl.DateTimeFormat('en-US', { timeZone: tz }); zoneOk.set(tz, true); }
    catch { zoneOk.set(tz, false); console.warn(`Dropping cities in unknown time zone: ${tz}`); }
  }
  return zoneOk.get(tz);
}

// GeoNames columns (zero-based): 1 name, 2 asciiname, 8 country code, 10 admin1 code, 14 population, 17 timezone.
const rows = lines('cities15000.txt')
  .filter(f => f[17] && validZone(f[17]))
  .map(f => ({ name: clean(f[1]), ascii: clean(f[2]), cc: f[8], region: admin1.get(`${f[8]}.${f[10]}`) || '', tz: f[17], pop: Number(f[14]) || 0 }))
  .sort((a, b) => b.pop - a.pop);

const zones = [...new Set(rows.map(r => r.tz))].sort();
const regions = [...new Set(rows.map(r => r.region).filter(Boolean))].sort();
const zi = new Map(zones.map((z, i) => [z, i]));
const ri = new Map(regions.map((r, i) => [r, i]));
const body = rows.map(r => [r.name, r.ascii === r.name ? '' : r.ascii, r.cc, r.region ? ri.get(r.region) : '', zi.get(r.tz)].join('|')).join('\n');

writeFileSync(out, `// Generated by tools/build-cities.mjs from GeoNames cities15000 (CC BY 4.0, https://www.geonames.org/). Do not edit.
// One row per city, largest first: name|ascii name if different|country code|region index|zone index
export const zones = ${JSON.stringify(zones)};
export const regions = ${JSON.stringify(regions)};
export const cities = ${JSON.stringify(body)};
`);
console.log(`Wrote ${rows.length} cities in ${zones.length} time zones to public/js/cities.js`);
